oldDjango/tcc/meu_projeto/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('meu_projetos.urls', namespace='meu_projetos')),
    url(r'^users/', include('users.urls', namespace='users')),
]

oldDjango/tcc/meu_projetos/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    #Mostra os servidores
    url(r'^servidores/$', views.servidores, name='servidores'),
    url(r'^servidores/(?P<servidor_id>\d+)/$', views.servidor, name='servidor' ),
    url(r'^novo_servidor/$', views.novo_servidor, name='novo_servidor' ),
]

oldDjango/tcc/users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login

from . import views

urlpatterns = [
    url(r'^login/$', login, {'template_name': 'users/login.html'},name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^register/$', views.register, name='register'),
]

oldDjango/tcc/meu_projetos/models.py
from django.db import models
from django.contrib.auth.models import User

class Servidor(models.Model):
    nome = models.CharField(max_length=100)
    owner = models.ForeignKey(User)

    def __str__(self):
        return self.nome

class Entrada(models.Model):
    servidor = models.ForeignKey(Servidor)
    produto = models.CharField(max_length=50)
    cveid = models.CharField(max_length=50)
    tipo = models.CharField(max_length=200)
    dataCorrecao = models.CharField(max_length=50)
    nota = models.CharField(max_length=10)
    tipoAcesso = models.CharField(max_length=200)
    comentario = models.TextField()

    class Meta:
        verbose_name_plural = 'entradas'

    def __str__(self):
        return self.produto+ " - " +self.comentario[:50] + "..."

oldDjango/tcc/users/models.py
from django.db import models

# Create your models here.

oldDjango/tcc/meu_projetos/forms.py
from django import forms
from .models import Servidor, Entrada

class ServidorForm(forms.ModelForm):
    class Meta:
        model = Servidor
        fields = ['nome']
        labels = {'nome' : ''}

class EntradaForm(forms.ModelForm):
    class Meta:
        model = Entrada
        fields = ['produto']

oldDjango/tcc/meu_projetos/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required

from .models import Servidor, Entrada
from .forms import ServidorForm, EntradaForm
from meu_projetos.scraping import scrapy


def index(request):
    return render(request, 'meu_projetos/index.html')

@login_required
def servidores(request):
    servidores = Servidor.objects.filter(owner=request.user).order_by('id')
    context = {'servidores':servidores}
    return render(request, 'meu_projetos/servidores.html', context )

@login_required
def servidor(request, servidor_id):
    servidor = Servidor.objects.get(id=servidor_id)
    entradas = servidor.entrada_set.all()
    if servidor.owner != request.user:
        raise Http404
    # entradas = servidor.entrada_set.order_by('-id')
    context = {'servidor':servidor, 'entradas':entradas}
    return render(request, 'meu_projetos/servidor.html', context)

@login_required
def novo_servidor(request):
    if request.method != 'POST':
        form = ServidorForm()
    else:
        form = ServidorForm(request.POST)
        if form.is_valid():
            novo_servidor = form.save(commit=False)
            novo_servidor.owner = request.user
            novo_servidor.save()
            #pega o nome do servidor e realiza scrapy
            s = Servidor.objects.all()
            lista = str(list(s)[-1]) #captura último elemento inserido no banco de dados
            scrapy(lista)
            return HttpResponseRedirect(reverse('meu_projetos:servidores'))
    context = {'form':form}
    return render(request, 'meu_projetos/novo_servidor.html', context)

oldDjango/tcc/users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.forms import UserCreationForm

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('meu_projetos:index'))

def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            authenticated_user = authenticate(username=new_user.username, password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('meu_projetos:index'))
    context = {'form': form}
    return render(request, 'users/register.html', context)

oldDjango/tcc/meu_projetos/templates/meu_projetos/base.html
<p>
    <a href="{% url 'meu_projetos:index' %}">Home</a> -
    <a href="{% url 'meu_projetos:servidores' %}">Servidores</a> -
    {% if user.is_authenticated %}
        Olá, {{ user.username }}<a href="{% url 'users:logout' %}">(logout).</a>
    {% else %}
        <a href="{% url 'users:register' %}">register</a> -
        <a href="{% url 'users:login' %}">Login</a>
    {% endif %}
</p>
{% block content %}{% endblock content %}

oldDjango/tcc/meu_projetos/templates/meu_projetos/index.html
{% extends "meu_projetos/base.html" %}

{% block content %}

<p>Meu Projeto</p>
<p>Meu projeto ajuda você a acompanhar o seu aprendizado, para qualquer tópico que estiver aprendendo. </p>

{% endblock content %}

oldDjango/tcc/meu_projetos/templates/meu_projetos/novo_servidor.html
{% extends 'meu_projetos/base.html' %}
{% block content %}
    <p>Novo Servidor:</p>
    <form action="{% url 'meu_projetos:novo_servidor' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Adicionar</button>
    </form>
{% endblock content %}

oldDjango/tcc/meu_projetos/templates/meu_projetos/servidor.html
{% extends 'meu_projetos/base.html' %}
{% block content %}
<p>Servidor: {{ servidor }}</p>
<p>Resultados:</p>
<ul>
    {% for entrada in entradas %}
        <li>
            <p>{{ entrada.produto }}</p>
            <p>cveid: {{ entrada.cveid }}</p>
            <p>tipo: {{ entrada.tipo }}</p>
            <p>dataCorrecao: {{ entrada.dataCorrecao }}</p>
            <p>nota: {{ entrada.nota }}</p>
            <p>tipoAcesso: {{ entrada.tipoAcesso }}</p>
            <p>comentario: {{ entrada.comentario }}</p>
        </li>
    {% empty %}
        <li>
            Não há registros.
        </li>
    {% endfor %}
</ul>
{% endblock content %}

oldDjango/tcc/meu_projetos/templates/meu_projetos/servidores.html
{% extends 'meu_projetos/base.html' %}
{% block content %}
<p>Servidores</p>
    <ul>
        {% for servidor in servidores %}
        <li>
            <a href="{% url 'meu_projetos:servidor' servidor.id %}">{{ servidor }}</a>
        </li>
        {% empty %}
        <li>Não servidores cadastrados.</li>
        {% endfor %}
    </ul>
    <a href="{% url 'meu_projetos:novo_servidor' %}">Adicionar Servidor</a>
{% endblock content %}

oldDjango/tcc/users/templates/users/login.html
{% extends "meu_projetos/base.html" %}
{% block content %}
    {% if form.errors %}
        <p>Login incorreto. Tente novamente.</p>
    {% endif %}
    <form method="post" action="{% url 'users:login' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Login</button>
        <input type="hidden" name="next" value="{% url 'meu_projetos:index' %}" />
    </form>
{% endblock content %}

oldDjango/tcc/users/templates/users/register.html
{% extends "meu_projetos/base.html" %}
{% block content %}
    <form method="post" action="{% url 'users:register' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">register</button>
    <input type="hidden" name="next" value="{% url 'meu_projetos:index' %}" />
    </form>
{% endblock content %}